In [64]:
import numpy as np

Create a NumPy array of integers from 1 to 10 (inclusive). 

In [65]:
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
b=np.random.randint(0,10,10)
b

array([9, 0, 7, 9, 6, 8, 3, 8, 6, 5], dtype=int32)

2. Reshape the array from the previous question into a 2x5 matrix.

In [67]:
a.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [68]:
b.reshape(2,5)

array([[9, 0, 7, 9, 6],
       [8, 3, 8, 6, 5]], dtype=int32)

3. Perform element-wise multiplication of two NumPy arrays: 

In [69]:
a+b

array([10,  2, 10, 13, 11, 14, 10, 16, 15, 15])

Create one multidimensional array of shape (3,4,2) and perform 
indexing and slicing on it. 

In [70]:
c=np.arange(24).reshape(3,4,2)
c

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [71]:
c[::2,0,::2]

array([[ 0],
       [16]])

. Generate a 3x3 matrix with random values between 0 and 1.

In [72]:
a=np.zeros([3,3],'i')
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [73]:
a=np.ones([3,3],'i')
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

6. Create two 2d array and perform hstack and vstack.

In [74]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.sort(a,axis=1)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [84]:
np.sort(a,axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])