In [1]:
import numpy as np

pip install numpy 

In [2]:
a = np.array([1,2,3,4])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
a.shape

(4,)

In [5]:
b = np.array([[1,2,3],[4,5,6]])

In [6]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
b.shape

(2, 3)

In [8]:
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [9]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [10]:
c.shape

(2, 2, 3)

In [11]:
d = a.astype('str')

In [12]:
d

array(['1', '2', '3', '4'], dtype='<U11')

In [13]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
b = np.arange(15,155,15).reshape(5,2)
b

array([[ 15,  30],
       [ 45,  60],
       [ 75,  90],
       [105, 120],
       [135, 150]])

In [15]:
b.reshape(5,2)

array([[ 15,  30],
       [ 45,  60],
       [ 75,  90],
       [105, 120],
       [135, 150]])

In [22]:
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [24]:
np.ones((5,4),'i')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [25]:
np.zeros((3,4),'i')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [30]:
np.random.random((3,3))

array([[0.32386871, 0.40599504, 0.29413275],
       [0.88038426, 0.5344583 , 0.74417179],
       [0.21451902, 0.9136159 , 0.92991081]])

In [31]:
np.random.randint(1,150,16)

array([ 20,  42, 120,  91, 136,  11,  17,  86, 137,  10, 132,  45,  98,
        79,  63,  68])

In [32]:
b.ndim

2

In [33]:
c.ndim

3

In [34]:
c.shape

(2, 2, 3)

In [35]:
c.size

12

In [37]:
a*3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [38]:
a>2

array([False, False,  True,  True,  True,  True,  True,  True,  True])

In [39]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a ** np.array([2,3,2,3,2,3,2,2,2])

array([  1,   8,   9,  64,  25, 216,  49,  64,  81])

In [27]:
a = np.random.random((3,3))*100

In [28]:
a

array([[94.81838569, 97.36992602, 61.97527633],
       [57.66369007, 90.60947994, 13.64653133],
       [69.55980953, 32.46966928, 91.16031707]])

In [32]:
np.round(a)

array([[95., 97., 62.],
       [58., 91., 14.],
       [70., 32., 91.]])

In [33]:
np.floor(a)

array([[94., 97., 61.],
       [57., 90., 13.],
       [69., 32., 91.]])

In [34]:
np.ceil(a)

array([[95., 98., 62.],
       [58., 91., 14.],
       [70., 33., 92.]])

In [50]:
np.sum(a,axis=0) # 0-> col, 1 -> row

array([180.47587901,  78.30061041, 133.39679361])

In [37]:
a

array([[94.81838569, 97.36992602, 61.97527633],
       [57.66369007, 90.60947994, 13.64653133],
       [69.55980953, 32.46966928, 91.16031707]])

In [36]:
np.prod(a)
np.sum(a)

609.2730852562029

In [ ]:
np.min()
np.max()

np.mean()
np.median()

In [2]:
a1 = np.arange(5,25)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(18).reshape(3,2,3)

In [39]:
a1

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [61]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [62]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [63]:
a1

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [65]:
a1[8]  # indexing

13

In [40]:
a1[5:12:2]

array([10, 12, 14, 16])

In [68]:
a1[8:14:2]  #slicing

array([13, 15, 17])

In [69]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
# 0,3,8,11
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [46]:
# 1,3,9,11
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [44]:
a2[1,1]
a2[2,3]

11

In [ ]:
# 0,3,8,11
#4,6,8,10
# 2,6,10
# 4,7,8,11
# 5,6,9,10
# 1,2,9,10
# 4,5,8,9

In [86]:
# 1,3,9,11
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [84]:
# 0,2,8,10
a2[::2,0:3:2]

array([[ 0,  2],
       [ 8, 10]])

In [81]:
# 5,6,9,10
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [76]:
# 2,3,10,11
a2[::2,2:]

array([[ 2,  3],
       [10, 11]])

In [70]:
a2[1,1]

5

In [71]:
a2[1,1::2]

array([5, 7])

In [73]:
a2[::2,1]

array([1, 9])

In [3]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [ ]:
# 0,1,3,4,12,13,15,16
# 0,2,6,8
# 6,9,12,15
# 7,8,10,11
# 3,4,15,16


In [13]:
a4 = np.arange(27).reshape(3,3,3)
a4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
# 0,2,6,8,9,11,15,17
#12, 13,15,16,21,22,24,25

# 3,5,12,14,21,23
# 1,2,7,8,10,11,16,17


In [12]:
# 0,2,12,14
a3[::2,0,::2]

array([[ 0,  2],
       [12, 14]])

In [8]:
# 3 ,9,15
a3[:,1,0]

array([ 3,  9, 15])

In [7]:
a3[2,1,2]

17

In [6]:
a3[1,1,1]

10

In [14]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [ ]:
# 0, 4,9,11,13
a3[[0,0,1,1],[0,1,1,1],[0,1,0,2]]  # advance/fancy indexing

array([ 0,  4,  9, 11])

In [16]:
a5 = np.random.randint(1,100,24).reshape(6,4)
a5

array([[44, 76, 63, 70],
       [81, 55, 65,  8],
       [13, 15, 84, 54],
       [10, 70, 86, 69],
       [ 2, 16, 31, 29],
       [74, 96, 95, 63]])

In [ ]:
a5[a5>50] # boolean indexing

array([76, 63, 70, 81, 55, 65, 84, 54, 70, 86, 69, 74, 96, 95, 63])

### Broadcasting

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.

The smaller array is “broadcast” across the larger array so that they have compatible shapes.

In [20]:
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

In [21]:
a+b

array([[ 6,  8, 10],
       [12, 14, 16]])

In [22]:
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

In [23]:
a+b

array([[0, 2, 4],
       [3, 5, 7]])

In [24]:
a,b

(array([[0, 1, 2],
        [3, 4, 5]]),
 array([[0, 1, 2]]))

In [ ]:
b = [[0,12],,
     [0,1,2]]

#### Broadcasting Rules

**1. Make the two arrays have the same number of dimensions.**<br>
- If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.<br>

**2. Make each dimension of the two arrays the same size.**<br>
- If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.
- If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.

In [25]:
a = np.arange(12).reshape(4,3)
b = np.arange(3)
a.shape,b.shape

((4, 3), (3,))

In [26]:
a+b

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [27]:
a = np.arange(12).reshape(3,4)
b = np.arange(3)
a+b

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [28]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [29]:
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [30]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)
a+b

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [31]:
a = np.arange(16).reshape(4,4)
b = np.arange(4).reshape(2,2)
a+b


ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 

np.sort

In [33]:
a = np.random.randint(1,100,15)
b = np.random.randint(1,100,24).reshape(6,4)

In [34]:
a,b

(array([ 6, 34, 83, 12,  9, 28, 53, 55, 91, 39, 68, 29, 45, 47, 71]),
 array([[40, 50, 66, 50],
        [18,  2, 79, 31],
        [74, 92, 49, 71],
        [34, 20, 83, 78],
        [52, 34, 96, 48],
        [28, 23, 10, 16]]))

In [36]:
a

array([ 6, 34, 83, 12,  9, 28, 53, 55, 91, 39, 68, 29, 45, 47, 71])

In [37]:
np.sort(a)

array([ 6,  9, 12, 28, 29, 34, 39, 45, 47, 53, 55, 68, 71, 83, 91])

In [38]:
np.sort(a)[::-1]

array([91, 83, 71, 68, 55, 53, 47, 45, 39, 34, 29, 28, 12,  9,  6])

In [39]:
b

array([[40, 50, 66, 50],
       [18,  2, 79, 31],
       [74, 92, 49, 71],
       [34, 20, 83, 78],
       [52, 34, 96, 48],
       [28, 23, 10, 16]])

In [40]:
np.sort(b) #default rows


array([[40, 50, 50, 66],
       [ 2, 18, 31, 79],
       [49, 71, 74, 92],
       [20, 34, 78, 83],
       [34, 48, 52, 96],
       [10, 16, 23, 28]])

In [41]:
np.sort(b,axis=0) 


array([[18,  2, 10, 16],
       [28, 20, 49, 31],
       [34, 23, 66, 48],
       [40, 34, 79, 50],
       [52, 50, 83, 71],
       [74, 92, 96, 78]])

Np.append

In [42]:
np.append(a,600)

array([  6,  34,  83,  12,   9,  28,  53,  55,  91,  39,  68,  29,  45,
        47,  71, 600])

In [43]:
b

array([[40, 50, 66, 50],
       [18,  2, 79, 31],
       [74, 92, 49, 71],
       [34, 20, 83, 78],
       [52, 34, 96, 48],
       [28, 23, 10, 16]])

In [44]:
c = [[1],
     [2],
     [2],
     [4],
     [5],
     [6]]

In [46]:
np.append(b,c,axis=1)

array([[40, 50, 66, 50,  1],
       [18,  2, 79, 31,  2],
       [74, 92, 49, 71,  2],
       [34, 20, 83, 78,  4],
       [52, 34, 96, 48,  5],
       [28, 23, 10, 16,  6]])

In [48]:
e=[[1,2,3,4]]
np.append(b,e,axis=0)

array([[40, 50, 66, 50],
       [18,  2, 79, 31],
       [74, 92, 49, 71],
       [34, 20, 83, 78],
       [52, 34, 96, 48],
       [28, 23, 10, 16],
       [ 1,  2,  3,  4]])