In [11]:
import numpy as np

In [12]:
a=np.array([1,2,3,4])

In [13]:
a

array([1, 2, 3, 4])

In [14]:
a.shape

(4,)

In [15]:
b=np.array([[1,2,3],[4,5,6]])

In [16]:
b.shape

(2, 3)

In [17]:
b=np.arange(15,155,15).reshape(5,2)
b

array([[ 15,  30],
       [ 45,  60],
       [ 75,  90],
       [105, 120],
       [135, 150]])

In [18]:
np.random.randint(1,150,15)

array([109,  26,  39,  82, 125,  68,  93,  57,  44,  16,  83, 123,  63,
        58,  21], dtype=int32)

In [19]:
np.sum(b,axis=1)

array([ 45, 105, 165, 225, 285])

In [27]:
a3=([[[0,1,2],[3,4,5],[6,7,8,9],[9,10,11],[12,13,14],[15,16,17],[18,19,20],[21,22,23],[24,25,26]]])

a3

[[[0, 1, 2],
  [3, 4, 5],
  [6, 7, 8, 9],
  [9, 10, 11],
  [12, 13, 14],
  [15, 16, 17],
  [18, 19, 20],
  [21, 22, 23],
  [24, 25, 26]]]